(* prompt/dev/todo.ebnf *)

(* ========================================================================== *)
(* TODO: HOW TO DESCRIBE PROGRAM DESIGN                                       *)
(* ========================================================================== *)

indent
  = "  "
  ;

todo_path
  = "todo.md"
  ;


todo_file
  = { comment | list }
  ;

(* ========================================================================== *)
(* COMMENT BLOCK                                                              *)
(* ========================================================================== *)

comment
  = "#", text, eol
  ;

(* ========================================================================== *)
(* LIST BLOCK                                                                 *)
(* ========================================================================== *)

list
  = identifier, eol, body
  ;

body
  = step, { step }
  ;

step
  = indent, "-", [ text | call ], eol
  ;

call
  = "@", identifier
  ;

(* ========================================================================== *)
(* END OF FILE                                                                *)
(* ========================================================================== *)

identifier
  = ? regex:/[a-zA-Z_][a-zA-Z0-9_]*/ ?
  ;

(*
  NONE.
  - MUST "length(text) < 80"
  - MUST "text does not contain newlines"
  - MUST "text is imperative or interrogative"
*)
text
  = ? regex:/[^\r\n]*/ ?
  ;

eol
  = "\n"
  | "\r\n"
  ;


(* ========================================================================== *)
(* EXAMPLE                                                                    *)
(* ========================================================================== *)


(*
  # This is a comment block.
  # It can have multiple lines.

  task
    - do something important.
    - do another thing.

  plan
    - do the first step.
    - do the second step.
    - @ task
    - do the third step.
*)
