(* prompts/pi/core/gen-exp-file.ebnf *)

(* ========================================================================== *)
(* HOW TO WRITE AN EXPERIENCE FILE                                            *)
(* ========================================================================== *)

exp_file = header , body , footer ;

(* ========================================================================== *)
(* HEADER                                                                     *)
(* ========================================================================== *)

header = path_comment , desc_comment, eol ;

path_comment = "<!--", path, "-->", eol ;
desc_comment = "<!--", desc, "-->", eol ;

path = ? this a file system path or URL link ? ;
desc = ? regex:/[^\n\r]*/ ? ;

(* ========================================================================== *)
(* BODY                                                                       *)
(* ========================================================================== *)

body = steps, [ notes ] ;

steps = "STEP.", eol, step , eol ;
notes = "NOTE.", eol, note , eol ;

step = line, { line } ;
note = line, { line } ;
line = "-", text, eol ;

(* ========================================================================== *)
(* FOOTER                                                                     *)
(* ========================================================================== *)

footer = "---", eol ;

(* ========================================================================== *)
(* BASIC ELEMENTS                                                             *)
(* ========================================================================== *)

(*
  NONE.
  - os path or command must use commonmark inline code syntax
    e.g. `/tmp/hi.tmp`, `echo "hello world!"`
  - link must use commonmark link syntax
    e.g. [label](url)
*)
text = ? regex:/[^\n\r]*/ ? ;
eol  = "\n" | "\r\n" ;
